services:
  mysql:
    image: mysql:8.4
    env_file: env_vars
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
  mongo:
    image: mongo:7
    env_file: env_vars
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  memcache:
    image: memcached
    ports:
      - 11211:11211
  meilisearch:
    image: getmeili/meilisearch:v1.8.4
    env_file: env_vars
    ports:
      - 7700:7700

volumes:
  mysql_data:
  mongo_data:
