services:
  mysql:
    image: mysql:8.4
    env_file: env_vars
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: mysql-entrypoints.d
        target: /docker-entrypoint-initdb.d/
        read_only: true
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: 'edxapp'
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: mongo-entrypoints.d
        target: /docker-entrypoint-initdb.d/
        read_only: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  memcache:
    image: memcached
    ports:
      - 11211:11211
  meilisearch:
    image: getmeili/meilisearch:v1.8.4
    env_file: env_vars
    ports:
      - 7700:7700
