[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openedx-site"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "openedx-platform",
    # uv has a weird behavior where is doesn't consistently respect pinned
    # versions. This constraint exists upstream in openedx-platform, but
    # we have to re-specify it here to ensure that we get setuptools<=81
    # (before pkg_resources was removed).
    "setuptools<82",
]

[project.optional-dependencies]
development = [
    "openedx-platform[development]"
]

[tool.uv.sources]
openedx-platform = { path = "../openedx-platform", editable = true }
